/**
 * Master keyword list for AliExpress product discovery.
 * Used by pintostudio~aliexpress-product-search Apify actor.
 * 238 keywords across all major dropshipping categories.
 */

export const SCRAPER_TERMS: string[] = [
  // ── Pet (high velocity) ────────────────────────────────────────────────────
  'dog harness',
  'dog car seat',
  'dog anxiety wrap',
  'cat tunnel toy',
  'pet water fountain',
  'dog paw cleaner',
  'cat litter box enclosed',
  'dog cooling mat',
  'pet camera treat dispenser',
  'dog training collar',
  'puppy crate',
  'cat scratcher lounge',
  'dog grooming glove',
  'dog seatbelt',
  'anti pull dog harness',
  'dog puzzle toy',
  'cat feather wand toy',
  'dog slow feeder bowl',
  'pet stroller',
  'dog ramp stairs',

  // ── Beauty & Skincare ──────────────────────────────────────────────────────
  'gua sha tool',
  'ice roller face',
  'facial cleansing brush',
  'blackhead remover vacuum',
  'silk pillowcase',
  'eyelash curler heated',
  'derma roller',
  'jade roller face',
  'pore vacuum suction',
  'eyebrow lamination kit',
  'hair growth serum',
  'nail gel kit',
  'lash lift kit',
  'scalp massager',
  'vitamin c serum',
  'retinol serum',
  'neck firming cream',
  'cellulite massager',
  'body sculpting tool',
  'lip plumper device',
  'eyelash growth serum',
  'face lifting tool',
  'double eyelid tape',
  'hair removal device ipl',

  // ── Home & Kitchen ─────────────────────────────────────────────────────────
  'fridge organiser bins',
  'lazy susan turntable',
  'pot rack wall mount',
  'bread box counter',
  'compost bin kitchen',
  'silicone food bag',
  'spice rack organiser',
  'cutting board set',
  'kitchen utensil holder',
  'cast iron skillet',
  'pour over coffee maker',
  'cold brew coffee maker',
  'electric egg cooker',
  'air fryer accessories set',
  'vacuum sealer bags',
  'kitchen scale digital',
  'salad spinner',
  'avocado slicer',
  'mandoline slicer',
  'herb stripper',
  'garlic press stainless',
  'lemon squeezer',
  'storage containers glass',
  'drawer organiser kitchen',
  'coffee grinder manual',

  // ── Home Decor & Cleaning ─────────────────────────────────────────────────
  'wall shelf floating',
  'picture frames set',
  'throw blanket chunky knit',
  'fairy lights bedroom',
  'desk plant pot',
  'scented candle soy',
  'diffuser essential oil',
  'toilet brush hidden',
  'shower caddy tension pole',
  'makeup organiser drawer',
  'cable management box',
  'under bed storage bags',
  'door organiser hanging',
  'boho wall hanging macrame',
  'bath mat non slip',
  'towel hook adhesive',
  'laundry basket foldable',
  'shoe rack stackable',

  // ── Fitness & Health ──────────────────────────────────────────────────────
  'resistance bands set',
  'ab roller wheel',
  'yoga block set',
  'jump rope weighted',
  'massage gun mini',
  'foam roller deep tissue',
  'pull up bar doorframe',
  'balance board wobble',
  'resistance loop bands',
  'yoga mat non slip thick',
  'grip strength trainer',
  'posture corrector back',
  'acupuncture mat pillow',
  'knee brace support',
  'ankle weights',
  'battle ropes',
  'suspension trainer',
  'booty band hip thrust',
  'core sliders fitness',
  'push up bars handles',
  'dip bar home',
  'kettlebell adjustable',

  // ── Sleep & Wellness ─────────────────────────────────────────────────────
  'weighted blanket 7kg',
  'white noise machine sleep',
  'sleep mask silk',
  'mouth tape sleeping',
  'nasal strips snoring',
  'magnesium spray',
  'eye massager electric',
  'back stretcher lumbar',
  'cervical neck traction',
  'grounding mat earthing',
  'heating pad back',
  'cold therapy gel pack',

  // ── Baby & Kids ──────────────────────────────────────────────────────────
  'baby monitor camera',
  'baby white noise machine',
  'baby carrier wrap',
  'silicone baby bib',
  'reusable swim nappy',
  'foam play mat tiles',
  'baby food maker',
  'teething toy silicone',
  'baby nail trimmer electric',
  'breastfeeding pillow',
  'potty training seat',
  'stroller organiser bag',
  'kids art supply set',
  'magnetic drawing board kids',
  'sensory fidget toy',
  'kids telescope',
  'bath toys toddler',
  'kids camera',

  // ── Electronics & Gadgets ────────────────────────────────────────────────
  'led strip lights bluetooth',
  'wireless charging pad fast',
  'phone stand desk adjustable',
  'laptop stand adjustable',
  'webcam ring light',
  'portable projector mini',
  'smart plug wifi',
  'solar garden lights',
  'usb hub multiport',
  'bluetooth tracker',
  'screen cleaning kit',
  'cable clips desk',
  'gaming headset stand',
  'monitor light bar desk',
  'power bank 20000mah',
  'car phone mount magnetic',
  'wireless earbuds charging case',
  'mechanical keyboard',
  'mouse pad xl desk',
  'webcam 1080p',

  // ── Automotive ───────────────────────────────────────────────────────────
  'car organiser back seat',
  'windshield sun shade',
  'car seat gap filler',
  'trunk organiser cargo',
  'steering wheel cover',
  'car air freshener vent',
  'car trash can mini',
  'car cleaning gel slime',
  'dash cam front rear',
  'tyre inflator portable',
  'jump starter portable',
  'car seat cushion',

  // ── Office & Productivity ────────────────────────────────────────────────
  'desk organiser set',
  'ergonomic mouse pad wrist',
  'monitor riser stand',
  'document scanner portable',
  'pen holder desk',
  'whiteboard desktop',
  'planner notebook undated',
  'blue light glasses',
  'laptop bag waterproof',
  'charging station multi device',
  'sticky note holder',
  'desk plant succulent',

  // ── Outdoor & Camping ────────────────────────────────────────────────────
  'camping lantern rechargeable',
  'water filter straw',
  'fire starter kit',
  'hammock lightweight',
  'trekking poles folding',
  'dry bag waterproof',
  'camping cookware set',
  'headlamp rechargeable',
  'survival paracord bracelet',
  'insulated water bottle',
  'stainless steel straw set',
  'foldable camping chair',
  'tent footprint groundsheet',
  'hiking backpack',
  'sun hat wide brim',

  // ── Fashion Accessories ──────────────────────────────────────────────────
  'crossbody bag women',
  'tote bag canvas large',
  'backpack anti theft',
  'wallet rfid blocking',
  'sunglasses polarised women',
  'hair clip claw large',
  'pearl hair pins set',
  'silk hair scrunchies',
  'jewellery organiser travel',
  'ring set women',
  'men leather bracelet',
  'watch women minimalist',
  'belt leather men',
  'bucket hat women',
  'cap embroidered',

  // ── Garden ───────────────────────────────────────────────────────────────
  'garden kneeler stool',
  'hose nozzle adjustable',
  'planting dibber tool',
  'garden gloves cut resistant',
  'self watering planter',
  'grow light led indoor',
  'seed starter kit indoor',
  'rain gauge garden',
  'bird feeder window',

  // ── 2025 Trending ────────────────────────────────────────────────────────
  'stanley cup accessories',
  'pilates reformer mini',
  'cold plunge tub portable',
  'sauna blanket infrared',
  'red light therapy mask',
  'microcurrent face device',
  'lash serum growth',
  'hair towel microfibre',
  'charcuterie board set',
  'pickleball paddle',
  'coffee table book',
  'aesthetic desk setup',
  'matcha whisk set',
  'sourdough bread basket',
  'gut health supplement',
  'collagen peptides powder',
  'mushroom coffee',
  'korean skincare set',
  'glass water bottle with straw',
  'stainless steel lunch box',

  // ── AU-Specific ──────────────────────────────────────────────────────────
  'bbq grill brush',
  'beach tent pop up',
  'rash guard uv protection',
  'snorkelling mask full face',
  'hydration backpack running',
  'mozzie repellent wristband',
  'reef safe sunscreen',
  'pool noodle float',
  'camping solar panel portable',
  'surfboard wax',
];

/** Category inference map for search terms */
export const TERM_CATEGORIES: Record<string, string> = {
  // Pet
  'dog harness': 'Pet', 'dog car seat': 'Pet', 'dog anxiety wrap': 'Pet',
  'cat tunnel toy': 'Pet', 'pet water fountain': 'Pet', 'dog paw cleaner': 'Pet',
  'cat litter box enclosed': 'Pet', 'dog cooling mat': 'Pet', 'pet camera treat dispenser': 'Pet',
  'dog training collar': 'Pet', 'puppy crate': 'Pet', 'cat scratcher lounge': 'Pet',
  'dog grooming glove': 'Pet', 'dog seatbelt': 'Pet', 'anti pull dog harness': 'Pet',
  'dog puzzle toy': 'Pet', 'cat feather wand toy': 'Pet', 'dog slow feeder bowl': 'Pet',
  'pet stroller': 'Pet', 'dog ramp stairs': 'Pet',
};
